### PR TITLE
Split aide ecriture

### PR DESCRIPTION
**Pull request by Grummfy**
It's still in progress following the PR #133 was accepted or not I will probably need to fix last non translated parts

### CODE REVIEW

**Comment by marmotz** [comment]
#133 merged
tell me when i can merge this one.

**Comment by Grummfy** [comment]
oki, I will work on it to finish it (probably friday). thanks

**Comment by Grummfy** [comment]
cela devrait-être bon

**Comment by marmotz** [comment]
You rocks !

**Pull request merged**
