### PR TITLE
Documentation refactoring #172

### PR DESCRIPTION
**Pull request by Grummfy**

### CODE REVIEW

**Comment by Grummfy** [comment]
preview : http://atoumpreviewdoc.readthedocs.org/en/refactoring-documentation/

**Comment by jubianchi** [comment]
on Safari (iOS) the layout does not work: the doc menu overlaps with the content.
image

**Comment by Grummfy** [comment]
@jubianchi is it already the case on the actual documentation or only on preview?

**Comment by mikaelrandy** [comment]
Seems good to me.
Good work :+1:

**Comment by jubianchi** [comment]
@Grummfy actual and preview have the same problem

**Comment by Grummfy** [comment]
thanks

**Pull request merged**
