### PR TITLE
add ci configuration to lint examples

### PR DESCRIPTION
**Pull request by agallou**

### CODE REVIEW

**Comment by agallou** [comment]
We van see a build example here : https://travis-ci.org/atoum/atoum-documentation/builds/133798215

Here is a sample of the output : 
```
⚑ Analysing file source//en/annotations.rst
⚑ Analysing file source//en/annotations/annotation-extension.inc.rst
 → Found code sample in line 0
 ✔ No syntax error detected
⚑ Analysing file source//en/annotations/annotation-php.inc.rst
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
⚑ Analysing file source//en/annotations/data-provider.inc.rst
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
⚑ Analysing file source//en/asserters.rst
⚑ Analysing file source//en/asserters/afterDestructionOf.inc.rst
 → Found code sample in line 0
 ✔ No syntax error detected
⚑ Analysing file source//en/asserters/array.inc.rst
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
 → Found code sample in line 0
 ✔ No syntax error detected
```

Thanks to @K-Phoen for the linter.

**Comment by Grummfy** [comment]
We should a some more stuff : 
- a helper or a command to run it locally ?
- in the README : how to run it locally to validate the changes

**Comment by K-Phoen** [comment]
Would it be easier for you if Rusty provided downloadable .phar executables? :)

**Comment by jubianchi** [comment]
@K-Phoen I'm not a super fan of Phar: it makes dealing with dependencie harder than with composer. Here we only have to put something in the json and composer deals with downloading, linking and locking everything ;)

**Comment by agallou** [comment]
ok. I will add both composer.json and composer.lock in the repository, and drop some lines about it in the readme.

**Comment by agallou** [comment]
PR updated with composer.json and composer.lock files commited, and documentation in README.md

**Pull request merged**
