### PR TITLE
Fix a link

### PR DESCRIPTION
**Pull request by Hywan**

### CODE REVIEW

**Comment by marmotz** [comment]
Your modification will not fix anything.
Please, look at others assertion files to see examples.

**Comment by Hywan** [comment]
screen shot 2015-03-09 at 10 48 10
There is a bug. I don't know how to fix it because I don't know the format :stuck_out_tongue:.

**Comment by marmotz** [comment]
That's why I suggest you to look other assertion files to see examples.
Or you can RTFM

**Comment by Hywan** [comment]
@marmotz This is not a correct way to talk to a contributor. You can give me a link to the documentation instead of saying RTFM (vulgar…). You can give an example instead of saying “your modification will fix anythin”, explain why instead of criticize.

**Comment by marmotz** [comment]
AH AH

**Comment by Hywan** [comment]
Why didn't you merge the PR?
You're offensive…

**Comment by marmotz** [comment]
Because, instead of trying to fix a single link, i've just fixed all links in #90 
Thank you to have report this mistakes.

**Pull request closed without merging**
