### PR TITLE
integration the documentation into the website

### PR DESCRIPTION
**Pull request by agallou**
Like that the users will be able to smoothly go back and forth from the documentation to the website.

Before : 
capture d ecran 2016-01-09 a 17 05 05

After : 
capture d ecran 2016-01-09 a 17 05 35

### CODE REVIEW

**Comment by Grummfy** [comment]
:+1:

**Comment by marmotz** [comment]
Is it possible to change documentation colors ?

**Comment by Grummfy** [comment]
we can change everything, so we can edit every style if we want

**Comment by marmotz** [comment]
In my opinion, we should integrate documentation with atoum website colors

**Comment by agallou** [comment]
i agree, it will be better with atoum's website colors.

I will try to propose something for that (will be interesting to see how https://github.com/atoum/atoum.github.io/issues/13 will be resolved)

Do we iterate on this and merge the menu integration ?

**Comment by agallou** [comment]
PR updated to improve the integration :
* forth column: 
  * added same backgroud as atoum's website
* header of second column : 
  * removed home logo
  * added atoum's logo
  * remove version (we only have one)
  * added links to the translations
  * added same backgroud as atoum's website
* bottom of the second column : 
  * we don't need all of read the docs infos, only the downloads links. They are now displayed directy.
* top of second column :
  * better color integration with the website
* bottom of the second column : 
   * remove link to the template

Here is what it looks like : 

capture d ecran 2016-01-10 a 13 40 34

**Comment by marmotz** [comment]
Nice.

atoum logo is... well... blue with brown is weird...

And I think you should update links and notes colors, too

**Comment by agallou** [comment]
any idea on how we should replace them ?

**Comment by marmotz** [comment]
With CSS, just like the rest of documentation ?

**Comment by agallou** [comment]
I mean. the colors. How should they look like ? (the note (for each type), and links). 
For the brown, you mean the breadcrumb ?

**Comment by agallou** [comment]
how about something like this for thie links ? 
capture d ecran 2016-01-10 a 21 50 32

**Comment by marmotz** [comment]
**brown vs blue :**
atoum theme is brown (light and dark) and the logo is blue. 
I wonder if we should redesign (or recolor) atoum logo (or atoum theme ? :p)

**links and notes colors :**
I have no opinion on the matter. You have done a great work for the rest of documentation.
I believe in you :)

**Comment by marmotz** [comment]
**links and notes colors :**
Yeah, it looks nice (except for the blue note, obviously :) )

**Comment by agallou** [comment]
for the logo, I think that's another issue.

how about this for notes and warnings ? 
capture d ecran 2016-01-10 a 22 05 46

**Comment by marmotz** [comment]
I love it

**Comment by agallou** [comment]
@marmotz PR updated

**Comment by marmotz** [comment]
GREAT JOB !

**Comment by marmotz** [comment]
Well it's not like in your screenshot :-/

**Comment by agallou** [comment]
thanks

**Comment by agallou** [comment]
what's the problem ?

**Comment by marmotz** [comment]
qu est ce qu atoum documentation atoum 1 0 0

**Comment by agallou** [comment]
I don't have this issue (tested on multiple browsers)
What's your browser/resolution ?

**Comment by marmotz** [comment]
Chrome 47 and Firefox 43 in multiple resolutions

**Comment by Grummfy** [comment]
http://docs.atoum.org/en/latest/

**Comment by Grummfy** [comment]
It's possible that RTD add some stuff

**Comment by agallou** [comment]
weird; I can't reproduce.
@Grummfy you have the same problem ?
@marmotz have you the same problem here http://test-rtd-layout.readthedocs.org/en/latest/ ?

**Comment by marmotz** [comment]
yes

**Comment by agallou** [comment]
thank to @Grummfy on IRC i've seen the problem. It appears on "small" resolutions. i'll make a PR to fix this.

**Comment by marmotz** [comment]
You're right, I don't have the problem on my 24" desktop

**Pull request merged**
